// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Oluwatosin Oghenewaire Thompson",
            "email": "oluwatosinthompson3@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cart/add": {
            "post": {
                "description": "Accept JSON data of cart data and returns valid response",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "handles adding items to cart",
                "parameters": [
                    {
                        "description": "Add items to cart",
                        "name": "Cart",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Cart"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authentication Token",
                        "name": "authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Item added to cart",
                        "schema": {
                            "$ref": "#/definitions/domain.Cart"
                        }
                    }
                }
            }
        },
        "/cart/delete/1/{reference}": {
            "delete": {
                "description": "Take the item-reference as a PARAMETER and returns valid response",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "handles deleting an item from cart",
                "responses": {
                    "200": {
                        "description": "deleted",
                        "schema": {
                            "$ref": "#/definitions/domain.Cart"
                        }
                    }
                }
            }
        },
        "/cart/delete/all": {
            "delete": {
                "description": "deletes all items from cart and returns valid response",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "handles deleting all item from cart",
                "responses": {
                    "200": {
                        "description": "all cart items deleted",
                        "schema": {
                            "$ref": "#/definitions/domain.Cart"
                        }
                    }
                }
            }
        },
        "/cart/update/increase/1": {
            "put": {
                "description": "Accept JSON data of cart data, takes the reference as a parameter to query the database and returns valid response",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "handles updating items in cart",
                "parameters": [
                    {
                        "description": "Update cart items",
                        "name": "Cart",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Cart"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authentication Token",
                        "name": "authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Item Updated",
                        "schema": {
                            "$ref": "#/definitions/domain.Cart"
                        }
                    }
                }
            }
        },
        "/cart/update/reduce/1": {
            "put": {
                "description": "Accept JSON data of cart data, takes the reference as a parameter to query the database and returns valid response",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "handles updating items in cart",
                "parameters": [
                    {
                        "description": "Update cart items",
                        "name": "Cart",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Cart"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authentication Token",
                        "name": "authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Item Updated",
                        "schema": {
                            "$ref": "#/definitions/domain.Cart"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Cart": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "price": {
                    "type": "integer"
                },
                "product_id": {
                    "type": "string"
                },
                "product_name": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "reference": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "petstore.swagger.io",
	BasePath:    "/v1",
	Schemes:     []string{},
	Title:       "GPI Barafiri Cart API",
	Description: "This is the barafiri cart microservice API",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
